[package]
name = "rpi-framebuffer"
version = "0.1.0"
license = "GPL-3.0-or-later"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
redshirt-hardware-interface = { path = "../../interfaces/hardware" }
redshirt-interface-interface = { path = "../../interfaces/interface" }
redshirt-log-interface = { path = "../../interfaces/log" }
redshirt-syscalls = { path = "../../interfaces/syscalls" }
parity-scale-codec = { version = "3.4.0", default-features = false }
