[package]
name = "redshirt-cli-kernel"
version = "0.1.0"
license = "GPL-3.0-or-later"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
edition = "2018"
publish = false
default-run = "redshirt-cli-kernel"

[dependencies]
async-std = "1.3"
futures = "0.3.1"
redshirt-core = { path = "../../core" }
redshirt-network-interface = { path = "../../interfaces/network" }
redshirt-stdout-hosted = { path = "../hosted-stdout" }
redshirt-stdout-interface = { path = "../../interfaces/stdout" }
redshirt-syscalls-interface = { path = "../../interfaces/syscalls" }
redshirt-tap-hosted = { path = "../hosted-tap" }
redshirt-time-hosted = { path = "../hosted-time" }
redshirt-time-interface = { path = "../../interfaces/time" }
parity-scale-codec = "1.0.5"
structopt = "0.3.5"
wasi = "0.9.0+wasi-snapshot-preview1"

[build-dependencies]
walkdir = "2.2.9"
