[package]
name = "wasm-timer"
version = "0.2.4"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
edition = "2018"

[dependencies]
pin-project = "1.0.1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
futures-timer = "2.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
redshirt-time-interface = { path = "../../../interfaces/time" }
