[package]
name = "nametbd-core"
version = "0.1.0"
license = "GPL-3.0-or-later"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
bs58 = { version = "0.3.0", default-features = false, features = ["alloc"] }
byteorder = { version = "1.3.2", default-features = false }
crossbeam = { version = "0.7.2", default-features = false }
futures = { version = "0.3.1", default-features = false }      # TODO: necessary?
hashbrown = { version = "0.6.0", default-features = false }
nametbd-interface-interface = { path = "../interfaces/interface", default-features = false }
nametbd-loader-interface = { path = "../interfaces/loader", default-features = false }
nametbd-syscalls-interface = { path = "../interfaces/syscalls", default-features = false }
nametbd-threads-interface = { path = "../interfaces/threads", default-features = false }
parity-scale-codec = { version = "1.0.5", default-features = false, features = ["derive"] } # TODO: might be unused
rand = "0.7"        # TODO: remove in favour of fine grained rand crates
rand_chacha = { version = "0.2.1", default-features = false }
rand_core = { version = "0.5.0", default-features = false }
rand_distr = { version = "0.2.2", default-features = false }
sha2 = { version = "0.8.0", default-features = false }
smallvec = { version = "1.0.0", default-features = false }
wat = "1.0.3"
# TODO: https://github.com/paritytech/wasmi/issues/218
wasmi = { git = "https://github.com/tomaka/wasmi", branch = "no-std", default-features = false, features = ["core"] }
