[package]
name = "http-server"
version = "0.1.0"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
futures = "0.3.1"
hyper = { version = "0.13.1", default-features = false }
log = "0.4.8"
redshirt-log-interface = { path = "../../interfaces/log" }
redshirt-network-interface = { path = "../../interfaces/network" }
redshirt-syscalls = { path = "../../interfaces/syscalls" }
redshirt-time-interface = { path = "../../interfaces/time" }
redshirt-tcp-interface = { path = "../../interfaces/tcp" }
