[package]
name = "pci-printer"
version = "0.1.0"
license = "GPL-3.0-or-later"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
fnv = { version = "1.0.7", default-features = false }
hashbrown = { version = "0.9.1", default-features = false }
lazy_static = "1"
log = "0.4"
redshirt-pci-interface = { path = "../../interfaces/pci" }
redshirt-log-interface = { path = "../../interfaces/log" }
redshirt-syscalls = { path = "../../interfaces/syscalls" }
parity-scale-codec = { version = "1.3.6", default-features = false }

[build-dependencies]
regex = "1.4.5"
