[package]
name = "redshirt-time-hosted"
version = "0.1.0"
license = "GPL-3.0-or-later"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
atomic = "0.5.0"
futures = "0.3.0"
futures-timer = "3.0"
redshirt-core = { path = "../../core" }
redshirt-interface-interface = { path = "../../interfaces/interface" }
redshirt-system-time-interface = { path = "../../interfaces/system-time" }
redshirt-time-interface = { path = "../../interfaces/time" }
lazy_static = "1.4"
