[package]
name = "redshirt-time-hosted"
version = "0.1.0"
license = "GPL-3.0-or-later"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
futures = "0.3.0"
futures-timer = "2.0"
redshirt-core = { path = "../../core" }
redshirt-interface-interface = { path = "../../interfaces/interface" }
redshirt-time-interface = { path = "../../interfaces/time" }
parity-scale-codec = "1.0.5"
lazy_static = "1.4"
