[package]
name = "compositor"
version = "0.1.0"
license = "GPL-3.0-or-later"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
ahash = { version = "0.6.2", default-features = false }
futures = "0.3.9"
hashbrown = { version = "0.9.1", default-features = false }
rand = "0.8.1"
redshirt-framebuffer-interface = { path = "../../interfaces/framebuffer" }
redshirt-interface-interface = { path = "../../interfaces/interface" }
redshirt-syscalls = { path = "../../interfaces/syscalls" }
redshirt-time-interface = { path = "../../interfaces/time" }
redshirt-video-output-interface = { path = "../../interfaces/video-output" }
